-- Intentionally empty.
--
-- This migration previously inserted 316 synthetic baseline events describing a
-- fictional organization. Those rows were the app's demo data; they have been
-- removed along with the simulator that generated them.
--
-- The file is kept rather than deleted because 0002 is already recorded as applied
-- in the deployed databases' d1_migrations table. Keeping it preserves a readable,
-- gap-free migration history; the tables it wrote to are dropped by
-- 0010_tenant_foundation.sql.
--
-- Do not add seed data here. Process data must come from observed Slack messages.
SELECT 1;
